
server:
  port: 8080

#数据库配置
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::memory::tool
    #username:
    #password:

mybatis:
  mapper-locations: classpath:mapper/*.xml

